-- ============================================================================
-- Civic Infra Mapper — Supabase schema
-- Safe to re-run: uses create-if-not-exists and drop-policy-if-exists.
-- ============================================================================

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  email text not null unique,
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  token_hash text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists sessions_user_id_idx on public.sessions(user_id);
create index if not exists sessions_expiration_idx on public.sessions(expires_at);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('Road', 'Footpath', 'Drainage', 'Streetlight', 'Waste', 'Water Supply', 'Public Space', 'Other')),
  description text not null check (char_length(description) between 1 and 3000),
  address text check (address is null or char_length(address) <= 300),
  latitude double precision check (latitude is null or latitude between -90 and 90),
  longitude double precision check (longitude is null or longitude between -180 and 180),
  photo text,
  reporter_name text not null default 'Anonymous' check (char_length(reporter_name) <= 80),
  severity text not null default 'Medium' check (severity in ('Low', 'Medium', 'High')),
  severity_rank integer generated always as (
    case severity when 'High' then 3 when 'Medium' then 2 else 1 end
  ) stored,
  status text not null default 'Pending' check (status in ('Pending', 'In Progress', 'Resolved')),
  user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check ((latitude is null) = (longitude is null))
);

create index if not exists reports_user_id_idx on public.reports(user_id);
create index if not exists reports_created_at_idx on public.reports(created_at desc);
create index if not exists reports_severity_created_idx on public.reports(severity_rank desc, created_at desc, id desc);
create index if not exists reports_category_created_idx on public.reports(category, created_at desc, id desc);
create index if not exists reports_status_created_idx on public.reports(status, created_at desc, id desc);

create table if not exists public.surveys (
  id bigint generated by default as identity primary key,
  name text check (name is null or char_length(name) <= 80),
  area text check (area is null or char_length(area) <= 120),
  roads integer not null default 3 check (roads between 1 and 5),
  drainage integer not null default 3 check (drainage between 1 and 5),
  streetlights integer not null default 3 check (streetlights between 1 and 5),
  waste integer not null default 3 check (waste between 1 and 5),
  water integer not null default 3 check (water between 1 and 5),
  footpaths integer not null default 3 check (footpaths between 1 and 5),
  biggest_problem text check (biggest_problem is null or char_length(biggest_problem) <= 80),
  suggestion text check (suggestion is null or char_length(suggestion) <= 3000),
  created_at timestamptz not null default now()
);

-- ---------- Row Level Security ----------
alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.reports enable row level security;
alter table public.surveys enable row level security;

drop policy if exists reports_public_realtime_read on public.reports;
create policy reports_public_realtime_read on public.reports
  for select to anon, authenticated using (true);

drop policy if exists surveys_public_realtime_read on public.surveys;
create policy surveys_public_realtime_read on public.surveys
  for select to anon, authenticated using (true);

-- ---------- Grants ----------
-- Public read for the two tables that power realtime updates in the UI
grant select on public.reports, public.surveys to anon, authenticated;

-- Users and sessions are server-only
revoke all on public.users, public.sessions from anon, authenticated;

-- The Express server (service_role) has full access
grant all on public.users, public.sessions, public.reports, public.surveys to service_role;
grant usage, select on all sequences in schema public to service_role;

-- ---------- Storage bucket for report photos ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('report-photos', 'report-photos', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists report_photos_public_read on storage.objects;
create policy report_photos_public_read on storage.objects
  for select to anon, authenticated using (bucket_id = 'report-photos');

-- ---------- Realtime ----------
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'reports'
  ) then
    alter publication supabase_realtime add table public.reports;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'surveys'
  ) then
    alter publication supabase_realtime add table public.surveys;
  end if;
end
$$;

-- ---------- Helper for resetting identity sequences ----------
create or replace function public.reset_civic_id_sequences()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform setval(pg_get_serial_sequence('public.users', 'id'),
    coalesce((select max(id) from public.users), 1),
    exists(select 1 from public.users));
  perform setval(pg_get_serial_sequence('public.reports', 'id'),
    coalesce((select max(id) from public.reports), 1),
    exists(select 1 from public.reports));
  perform setval(pg_get_serial_sequence('public.surveys', 'id'),
    coalesce((select max(id) from public.surveys), 1),
    exists(select 1 from public.surveys));
end
$$;

revoke all on function public.reset_civic_id_sequences() from public, anon, authenticated;
grant execute on function public.reset_civic_id_sequences() to service_role;